name: Update Repository Daily

on:
  schedule:
    - cron: '0 20 * * *'  # This cron syntax means the workflow will run every day at midnight UTC
    - cron: '33 19 * * *'
jobs:
  update-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Adjust this line based on your project's requirements

    - name: Run the update script
      run: |
        python metwoba.py  # Replace with the path to your script

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add -A
        git commit -m 'Daily update from GitHub Actions'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
